#!/bin/bash
cd ~
curl https://raw.github.com/fesplugas/rbenv-installer/master/bin/rbenv-installer | bash
. ~/.bashrc
# exec $SHELL -l
rbenv install 2.0.0-p0
rbenv global 2.0.0-p0
rbenv bootstrap
rbenv rehash
